# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sync some data with third parties


Resources:
    AssignArchetypeQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: assign-archetype-queue
            VisibilityTimeout: 601
    AssignArchetypeSqsQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Id: AssignArchetypeQueuePolicy
                Statement:
                    - Sid: Allow-SNS-SendMessage
                      Effect: Allow
                      Principal:
                          AWS: '*'
                      Action:
                          - sqs:SendMessage
                      Resource: !GetAtt AssignArchetypeQueue.Arn
                      Condition:
                          ArnEquals:
                              aws:SourceArn: arn:aws:sns:us-west-2:478062583808:archetype-assigned
            Queues:
                - !Ref AssignArchetypeQueue
    AssignArchetypeSnsSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Protocol: SQS
            Endpoint: !GetAtt AssignArchetypeQueue.Arn
            TopicArn: arn:aws:sns:us-west-2:478062583808:archetype-assigned

    ProcessAssignArchetypeFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-assign-archetype.default
            Runtime: nodejs16.x
            CodeUri: ./dist/process-assign-archetype
            Timeout: 120
            MemorySize: 4000
            ReservedConcurrentExecutions: 10
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - AmazonSNSFullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-assign-archetype
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt AssignArchetypeQueue.Arn
                        BatchSize: 1